create table public.clients_valuations (
  id uuid not null default gen_random_uuid (),
  created_at timestamp without time zone not null default now(),
  client_email text null,
  contract_type text null,
  advisor_id uuid null,
  pdf_proposal text null,
  status text null,
  proposal_date timestamp without time zone null,
  signature text null,
  signature_date timestamp without time zone null,
  "CUPS" text null,
  new_company text null,
  bank_ownership text null,
  saving_percentage real null,
  temp_client_name text not null default ''::text,
  temp_client_last_name text not null default ''::text,
  deleted boolean not null default false,
  deleted_reason text not null default ''::text,
  contract_id uuid null,
  pdf_invoice text null,
  temp_account_number text null,
  temp_dni text null,
  crs real null,
  temp_pdf_dni text null,
  temp_mobile_number text null,
  temp_ownership_change boolean not null default false,
  temp_ownership_change_pdf text null,
  temp_power_change boolean not null default false,
  temp_power_change_new_value real null,
  temp_paper_invoices boolean not null default false,
  temp_new_registration boolean not null default false,
  temp_account_ownership_pdf text null,
  temp_delegated_signature boolean not null default false,
  temp_delegated_signature_email text null,
  temp_selfconsumption boolean not null default false,
  max_power real null,
  new_rate text null,
  new_subrate text null,
  idioma text null,
  notificaciones boolean not null default false,
  deleted_at timestamp without time zone null,
  constraint clients_valuations_pkey primary key (id),
  constraint clients_valuations_advisor_id_fkey foreign KEY (advisor_id) references auth.users (id) on delete set null,
  constraint clients_valuations_contract_id_fkey foreign KEY (contract_id) references clients_contracts (id) on delete CASCADE
) TABLESPACE pg_default;