DROP VIEW IF EXISTS public._comparisons_detailed_phone CASCADE;

CREATE OR REPLACE VIEW public._comparisons_detailed_phone AS
SELECT DISTINCT
  rp.id,
  rp.created_at::timestamp without time zone AS created_at,
  rp.client_email,
  rp.advisor_id,
  rp.consumption_p1,
  rp.consumption_p2,
  rp.consumption_p3,
  rp.consumption_p4,
  rp.consumption_p5,
  rp.consumption_p6,
  rp.anual_consumption_p1,
  rp.anual_consumption_p2,
  rp.anual_consumption_p3,
  rp.anual_consumption_p4,
  rp.anual_consumption_p5,
  rp.anual_consumption_p6,
  rp.autoconsumo_precio,
  rp."precio_kw_P1",
  rp."precio_kw_P2",
  rp."precio_kw_P3",
  rp."precio_kw_P4",
  rp."precio_kw_P5",
  rp."precio_kw_P6",
  rp."precio_kwh_P1",
  rp."precio_kwh_P2",
  rp."precio_kwh_P3",
  rp."precio_kwh_P4",
  rp."precio_kwh_P5",
  rp."precio_kwh_P6",
  rp.total_consumption,
  rp.total_anual_consumption,
  rp.power_p1,
  rp.power_p2,
  rp.power_p3,
  rp.power_p4,
  rp.power_p5,
  rp.power_p6,
  rp.current_total_invoice,
  rp.surpluses,
  rp.total_surpluses_price,
  rp.power_surpluses,
  rp."VAT",
  rp.days,
  rp.pdf_invoice,
  rp.cups AS "CUPS",
  rp.address_id,
  rp.company,
  rp.rate_name,
  rp.invoice_month,
  rp.equipment_rental,
  rp.selfconsumption,
  rp.manual_data,
  rp.reactive,
  rp.valuation_id,
  rp.invoice_year,
  rp.meter_rental,
  rp.preferred_subrate,
  rp.new_company,
  rp.new_rate_name,
  rp.new_subrate_name,
  rp.price_pp1,
  rp.price_pp2,
  rp.price_pp3,
  rp.price_pp4,
  rp.price_pp5,
  rp.price_pp6,
  rp.price_cp1,
  rp.price_cp2,
  rp.price_cp3,
  rp.price_cp4,
  rp.price_cp5,
  rp.price_cp6,
  rp.price_surpluses,
  rp.total_power_price,
  rp.total_consumption_price,
  rp.new_total_price,
  rp.type,
  rp.temp_client_name,
  rp.temp_client_last_name,
  rp.type_filter,
  rp.deleted,
  rp.deleted_reason,
  NULL::timestamp AS deleted_at,
  rp.new_rate_id,
  rp.max_power,
  rp.speed_fiber,
  rp.mobile_lines,
  rp.mobile_total_gb,
  rp.fijo,
  rp.new_speed_fiber,
  rp.new_total_mobile_lines,
  rp.new_mobile_total_gb,
  rp.rate_pack,
  rp.phone_total_anual_price::integer AS phone_total_anual_price,
  rp.crs_id,
  rp.total_crs,
  rp.savings,
  rp.savings_yearly,
  rp.ranked_crs,
  rp.rank,
  false AS tarifa_plana,
  0.0::double precision AS iee_monthly,
  0.0::double precision AS iee,
  rp.new_total_price AS new_total_price_with_vat,
  COALESCE(
    rp.phone_total_anual_price::double precision,
    rp.new_total_price * 12::double precision
  ) AS new_total_yearly_price_with_vat,
  CASE
    WHEN rp.current_total_invoice > 0::numeric THEN (
      (rp.current_total_invoice * 12::numeric)::double precision - COALESCE(rp.phone_total_anual_price, 0::real)::double precision
    ) / NULLIF(
      rp.current_total_invoice * 12::numeric,
      0::numeric
    )::double precision
    ELSE 0.0::double precision
  END AS saving_percentage,
  us.supervisors,
  COALESCE(rp.temp_client_name, ''::text) AS client_name,
  COALESCE(rp.temp_client_last_name, ''::text) AS client_last_name,
  u.email AS advisor_email,
  u.name AS advisor_display_name,
  ARRAY[COALESCE(u.email, ''::text), 'All'::text] AS advisor_filter,
  EXTRACT(MONTH FROM rp.created_at)::text AS created_month,
  EXTRACT(YEAR FROM rp.created_at)::text AS created_year,
  concat_ws(', ', rp.client_email, rp.cups) AS search,
  ARRAY[rp.company, 'All'::text] AS company_filter,
  false AS cif,
  NULL::text AS region,
  0.0::numeric(8, 2) AS daily_maintenance_with_vat,
  false AS has_permanence,
  NULL::rate_mode_type AS rate_mode,
  0::real AS total_excedentes_precio,
  NULL::rate_mode_type AS rate_i_have,
  NULL::integer AS term_month,
  NULL::integer AS term_month_i_want,
  NULL::uuid[] AS excluded_company_ids,
  false AS wants_gdo,
  NULL::text AS temp_client_phone
FROM (
  SELECT
    rpr.id,
    rpr.created_at,
    rpr.client_email,
    rpr.advisor_id,
    0 AS consumption_p1,
    0 AS consumption_p2,
    0 AS consumption_p3,
    0 AS consumption_p4,
    0 AS consumption_p5,
    0 AS consumption_p6,
    0 AS anual_consumption_p1,
    0 AS anual_consumption_p2,
    0 AS anual_consumption_p3,
    0 AS anual_consumption_p4,
    0 AS anual_consumption_p5,
    0 AS anual_consumption_p6,
    0 AS autoconsumo_precio,
    0 AS "precio_kw_P1",
    0 AS "precio_kw_P2",
    0 AS "precio_kw_P3",
    0 AS "precio_kw_P4",
    0 AS "precio_kw_P5",
    0 AS "precio_kw_P6",
    0 AS "precio_kwh_P1",
    0 AS "precio_kwh_P2",
    0 AS "precio_kwh_P3",
    0 AS "precio_kwh_P4",
    0 AS "precio_kwh_P5",
    0 AS "precio_kwh_P6",
    0 AS total_consumption,
    0 AS total_anual_consumption,
    0 AS power_p1,
    0 AS power_p2,
    0 AS power_p3,
    0 AS power_p4,
    0 AS power_p5,
    0 AS power_p6,
    rpr.current_total_invoice,
    0 AS surpluses,
    0 AS total_surpluses_price,
    0 AS power_surpluses,
    0 AS "VAT",
    0 AS days,
    cp.pdf_invoice,
    ''::text AS cups,
    NULL::uuid AS address_id,
    rpr.company,
    ''::text AS rate_name,
    0 AS invoice_month,
    0 AS equipment_rental,
    false AS selfconsumption,
    true AS manual_data,
    0 AS reactive,
    cp.valuation_id,
    0 AS invoice_year,
    0 AS meter_rental,
    NULL::text AS preferred_subrate,
    rpr.new_company,
    rpr.new_rate_name,
    ''::text AS new_subrate_name,
    0 AS price_pp1,
    0 AS price_pp2,
    0 AS price_pp3,
    0 AS price_pp4,
    0 AS price_pp5,
    0 AS price_pp6,
    0 AS price_cp1,
    0 AS price_cp2,
    0 AS price_cp3,
    0 AS price_cp4,
    0 AS price_cp5,
    0 AS price_cp6,
    0 AS price_surpluses,
    0 AS total_power_price,
    0 AS total_consumption_price,
    rpr.new_total_price,
    rpr.type,
    COALESCE(cp.temp_client_name, ''::text) AS temp_client_name,
    COALESCE(cp.temp_client_last_name, ''::text) AS temp_client_last_name,
    ARRAY['phone'::text, 'All'::text] AS type_filter,
    cp.deleted,
    cp.deleted_reason,
    rpr.new_rate_id,
    0 AS max_power,
    rpr.speed_fiber,
    rpr.mobile_lines,
    rpr.mobile_total_gb,
    COALESCE(rpr.landline, cp.landline) AS fijo,
    NULL::integer AS new_speed_fiber,
    NULL::integer AS new_total_mobile_lines,
    NULL::integer AS new_mobile_total_gb,
    rpr.rate_pack,
    rpr.phone_total_anual_price,
    rpr.crs_id,
    rpr.total_crs,
    rpr.savings,
    rpr.savings_yearly,
    COALESCE(
      (
        COALESCE(rpr.current_total_invoice, 0::numeric) * 12::numeric
      )::double precision - COALESCE(rpr.phone_total_anual_price, 0::numeric)::double precision,
      0::double precision
    ) + COALESCE(rpr.total_crs, 0::numeric) * 4::double precision AS ranked_crs,
    1 AS rank
  FROM comparison_phone_results rpr
  LEFT JOIN comparison_phone cp ON cp.id = rpr.comparison_id
) rp
LEFT JOIN _users_supervisors us ON rp.advisor_id = us.user_id
LEFT JOIN users u ON u.user_id = rp.advisor_id
WHERE
  rp.rank = 1
  AND (
    rp.deleted IS NULL
    OR rp.deleted = FALSE
  );
