create view public._comparisons_detailed_phone as
select distinct
  rp.id,
  rp.created_at::timestamp without time zone as created_at,
  rp.client_email,
  rp.advisor_id,
  rp.consumption_p1,
  rp.consumption_p2,
  rp.consumption_p3,
  rp.consumption_p4,
  rp.consumption_p5,
  rp.consumption_p6,
  rp.anual_consumption_p1,
  rp.anual_consumption_p2,
  rp.anual_consumption_p3,
  rp.anual_consumption_p4,
  rp.anual_consumption_p5,
  rp.anual_consumption_p6,
  rp.autoconsumo_precio,
  rp."precio_kw_P1",
  rp."precio_kw_P2",
  rp."precio_kw_P3",
  rp."precio_kw_P4",
  rp."precio_kw_P5",
  rp."precio_kw_P6",
  rp."precio_kwh_P1",
  rp."precio_kwh_P2",
  rp."precio_kwh_P3",
  rp."precio_kwh_P4",
  rp."precio_kwh_P5",
  rp."precio_kwh_P6",
  rp.total_consumption,
  rp.total_anual_consumption,
  rp.power_p1,
  rp.power_p2,
  rp.power_p3,
  rp.power_p4,
  rp.power_p5,
  rp.power_p6,
  rp.current_total_invoice,
  rp.surpluses,
  rp.total_surpluses_price,
  rp.power_surpluses,
  rp."VAT",
  rp.days,
  rp.pdf_invoice,
  rp.cups as "CUPS",
  rp.address_id,
  rp.company,
  rp.rate_name,
  rp.invoice_month,
  rp.equipment_rental,
  rp.selfconsumption,
  rp.manual_data,
  rp.reactive,
  rp.valuation_id,
  rp.invoice_year,
  rp.meter_rental,
  rp.preferred_subrate,
  rp.new_company,
  rp.new_rate_name,
  rp.new_subrate_name,
  rp.price_pp1,
  rp.price_pp2,
  rp.price_pp3,
  rp.price_pp4,
  rp.price_pp5,
  rp.price_pp6,
  rp.price_cp1,
  rp.price_cp2,
  rp.price_cp3,
  rp.price_cp4,
  rp.price_cp5,
  rp.price_cp6,
  rp.price_surpluses,
  rp.total_power_price,
  rp.total_consumption_price,
  rp.new_total_price,
  rp.type,
  rp.temp_client_name,
  rp.temp_client_last_name,
  rp.type_filter,
  rp.deleted,
  rp.deleted_reason,
  null::timestamp without time zone as deleted_at,
  rp.new_rate_id,
  rp.max_power,
  rp.speed_fiber,
  rp.mobile_lines,
  rp.mobile_total_gb,
  rp.fijo,
  rp.new_speed_fiber,
  rp.new_total_mobile_lines,
  rp.new_mobile_total_gb,
  rp.rate_pack,
  rp.phone_total_anual_price::integer as phone_total_anual_price,
  rp.crs_id,
  rp.total_crs,
  rp.savings,
  rp.savings_yearly,
  rp.ranked_crs,
  rp.rank,
  false as tarifa_plana,
  0.0::double precision as iee_monthly,
  0.0::double precision as iee,
  rp.new_total_price as new_total_price_with_vat,
  COALESCE(
    rp.phone_total_anual_price::double precision,
    rp.new_total_price::double precision * 12::double precision
  ) as new_total_yearly_price_with_vat,
  case
    when rp.current_total_invoice > 0::numeric then (
      (rp.current_total_invoice * 12::numeric)::double precision - COALESCE(rp.phone_total_anual_price::real, 0::real)::double precision
    ) / NULLIF(
      rp.current_total_invoice * 12::numeric,
      0::numeric
    )::double precision
    else 0.0::double precision
  end as saving_percentage,
  us.supervisors,
  COALESCE(rp.temp_client_name, ''::text) as client_name,
  COALESCE(rp.temp_client_last_name, ''::text) as client_last_name,
  us.email as advisor_email,
  us.display_name as advisor_display_name,
  array[COALESCE(us.email, ''::text), 'All'::text] as advisor_filter,
  EXTRACT(
    month
    from
      rp.created_at
  )::text as created_month,
  EXTRACT(
    year
    from
      rp.created_at
  )::text as created_year,
  concat_ws(', '::text, rp.client_email, rp.cups) as search,
  array[rp.company, 'All'::text] as company_filter,
  false as cif,
  null::text as region,
  0.0::numeric(8, 2) as daily_maintenance_with_vat,
  false as has_permanence,
  null::rate_mode_type as rate_mode,
  0::real as total_excedentes_precio,
  null::rate_mode_type as rate_i_have,
  null::integer as term_month,
  null::integer as term_month_i_want,
  null::uuid[] as excluded_company_ids,
  false as wants_gdo,
  null::text as temp_client_phone
from
  (
    select
      rpr.id,
      rpr.created_at,
      rpr.client_email,
      rpr.advisor_id,
      0 as consumption_p1,
      0 as consumption_p2,
      0 as consumption_p3,
      0 as consumption_p4,
      0 as consumption_p5,
      0 as consumption_p6,
      0 as anual_consumption_p1,
      0 as anual_consumption_p2,
      0 as anual_consumption_p3,
      0 as anual_consumption_p4,
      0 as anual_consumption_p5,
      0 as anual_consumption_p6,
      0 as autoconsumo_precio,
      0 as "precio_kw_P1",
      0 as "precio_kw_P2",
      0 as "precio_kw_P3",
      0 as "precio_kw_P4",
      0 as "precio_kw_P5",
      0 as "precio_kw_P6",
      0 as "precio_kwh_P1",
      0 as "precio_kwh_P2",
      0 as "precio_kwh_P3",
      0 as "precio_kwh_P4",
      0 as "precio_kwh_P5",
      0 as "precio_kwh_P6",
      0 as total_consumption,
      0 as total_anual_consumption,
      0 as power_p1,
      0 as power_p2,
      0 as power_p3,
      0 as power_p4,
      0 as power_p5,
      0 as power_p6,
      rpr.current_total_invoice,
      0 as surpluses,
      0 as total_surpluses_price,
      0 as power_surpluses,
      0 as "VAT",
      0 as days,
      cp.pdf_invoice,
      ''::text as cups,
      null::uuid as address_id,
      rpr.company,
      ''::text as rate_name,
      0 as invoice_month,
      0 as equipment_rental,
      false as selfconsumption,
      true as manual_data,
      0 as reactive,
      cp.valuation_id,
      0 as invoice_year,
      0 as meter_rental,
      null::text as preferred_subrate,
      rpr.new_company,
      rpr.new_rate_name,
      ''::text as new_subrate_name,
      0 as price_pp1,
      0 as price_pp2,
      0 as price_pp3,
      0 as price_pp4,
      0 as price_pp5,
      0 as price_pp6,
      0 as price_cp1,
      0 as price_cp2,
      0 as price_cp3,
      0 as price_cp4,
      0 as price_cp5,
      0 as price_cp6,
      0 as price_surpluses,
      0 as total_power_price,
      0 as total_consumption_price,
      rpr.new_total_price,
      rpr.type,
      COALESCE(cp.temp_client_name, ''::text) as temp_client_name,
      COALESCE(cp.temp_client_last_name, ''::text) as temp_client_last_name,
      array['phone'::text, 'All'::text] as type_filter,
      cp.deleted,
      cp.deleted_reason,
      rpr.new_rate_id,
      0 as max_power,
      rpr.speed_fiber,
      rpr.mobile_lines,
      rpr.mobile_total_gb,
      COALESCE(rpr.landline, cp.landline) as fijo,
      null::integer as new_speed_fiber,
      null::integer as new_total_mobile_lines,
      null::integer as new_mobile_total_gb,
      rpr.rate_pack,
      rpr.phone_total_anual_price,
      rpr.crs_id,
      rpr.total_crs,
      rpr.savings,
      rpr.savings_yearly,
      COALESCE(
        (
          COALESCE(rpr.current_total_invoice, 0::numeric) * 12::numeric
        )::double precision - COALESCE(rpr.phone_total_anual_price, 0::numeric)::double precision,
        0::double precision
      ) + COALESCE(rpr.total_crs, 0::numeric)::double precision * 4::double precision as ranked_crs,
      1 as rank
    from
      comparison_phone_results rpr
      left join comparison_phone cp on cp.id = rpr.comparison_id
  ) rp
  left join _users_supervisors_all us on rp.advisor_id = us.user_id
where
  rp.rank = 1
  and (
    rp.deleted is null
    or rp.deleted = false
  );