create table public.comparison_3_0 (
  id uuid not null default gen_random_uuid (),
  created_at timestamp without time zone not null default now(),
  advisor_id uuid null,
  invoice_month integer null,
  consumption_p1 real not null default '0'::real,
  consumption_p2 real not null default '0'::real,
  consumption_p3 real not null default '0'::real,
  consumption_p4 real not null default '0'::real,
  consumption_p5 real not null default '0'::real,
  consumption_p6 real not null default '0'::real,
  power_p1 real not null default '0'::real,
  power_p2 real not null default '0'::real,
  power_p3 real not null default '0'::real,
  power_p4 real not null default '0'::real,
  power_p5 real not null default '0'::real,
  power_p6 real not null default '0'::real,
  current_total_invoice real not null default '0'::real,
  "VAT" real not null default '0'::real,
  power_days integer not null default 0,
  client_email text null,
  pdf_invoice text null,
  "CUPS" text null,
  address_id uuid null,
  rate_name text null,
  manual_data boolean not null default false,
  equipment_rental real not null default '0'::real,
  reactive real not null default '0'::real,
  valuation_id uuid null,
  invoice_year integer null,
  company text not null default ''::text,
  temp_client_name text not null default ''::text,
  temp_client_last_name text not null default ''::text,
  power_surpluses real not null default '0'::real,
  surpluses real not null default '0'::real,
  deleted boolean not null default false,
  deleted_reason text null,
  selfconsumption boolean not null default false,
  preferred_subrate text null,
  anual_consumption_p1 real null,
  anual_consumption_p2 real null,
  anual_consumption_p3 real null,
  anual_consumption_p4 real null,
  anual_consumption_p5 real null,
  anual_consumption_p6 real null,
  max_power real null default '0'::real,
  "precio_kwh_P1" real not null default 0,
  "precio_kwh_P2" real not null default 0,
  "precio_kwh_P3" real not null default 0,
  "precio_kwh_P4" real not null default 0,
  "precio_kwh_P5" real not null default 0,
  "precio_kwh_P6" real not null default 0,
  "precio_kw_P1" real not null default 0,
  "precio_kw_P2" real not null default 0,
  "precio_kw_P3" real not null default 0,
  "precio_kw_P4" real not null default 0,
  "precio_kw_P5" real not null default 0,
  "precio_kw_P6" real not null default 0,
  autoconsumo_precio real null default '0'::real,
  totalconsumo real null default '0'::real,
  totalpotencia real null default '0'::real,
  region text null default 'PENINSULA'::text,
  cif boolean null default false,
  source_type_id bigint not null default 0,
  rate_i_have public.rate_mode_type null,
  rate_i_want public.rate_mode_type null,
  wants_permanence boolean null,
  comparison_id uuid null,
  term_month_i_want numeric null,
  wants_gdo boolean not null default false,
  invoice_address text null,
  deleted_at timestamp without time zone null,
  temp_client_phone text null,
  excluded_company_ids uuid[] not null default '{}'::uuid[],
  constraint comparison_3_0_pkey primary key (id),
  constraint comparison_3_0_address_id_fkey foreign KEY (address_id) references clients_addresses (id),
  constraint comparison_3_0_advisor_id_fkey foreign KEY (advisor_id) references auth.users (id) on delete set null,
  constraint comparison_3_0_comparison_id_fkey foreign KEY (comparison_id) references comparisons (id) on delete CASCADE,
  constraint comparison_3_0_source_type_id_fkey foreign KEY (source_type_id) references source_type (id) on update CASCADE on delete set default,
  constraint comparison_3_0_valuation_id_fkey foreign KEY (valuation_id) references clients_valuations (id)
) TABLESPACE pg_default;

create index IF not exists idx_comparison_3_0_deleted_false on public.comparison_3_0 using btree (id) TABLESPACE pg_default
where
  (deleted = false);

create index IF not exists idx_comparison_3_0_created_at on public.comparison_3_0 using btree (created_at) TABLESPACE pg_default;

create index IF not exists idx_comparison_3_0_advisor on public.comparison_3_0 using btree (advisor_id) TABLESPACE pg_default;

create trigger trg_set_deleted_at BEFORE
update on comparison_3_0 for EACH row
execute FUNCTION set_deleted_at_on_delete ();